### ISSUE TITLE
Tighter integration with feathers-authentication-management

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/authentication#393]
`feathers-authentication-management` adds a `isVerified` flag to `user`. That can be used in a service hook to check a user is verified, after any checking that the user is authenticated.

Still it looks a bit wierd that the feathers-authentication ecosystem will authenticate a user with `isVerified === false`. I wonder if that flag, if it exists, should be checked by the ecosystem.

**Comment by marshallswain** [comment]
We definitely need a better way to integrate.  Is the user present in an `afterCreate` hook on the authentication service?  If so, we could just register an after hook that checks the user and throws an error to keep the token from going out.

**Comment by ekryski** [comment]
I'd like to revisit this and look at tweaking `feathers-authentication-management` to be a bit more generic so that the user isn't required to define any specific model attributes. I see it being pretty minor tweaks and also easier once we have some of the work slated for Auth 2.0 complete.
