### ISSUE TITLE
XXXOrRestrict undermines provider (security) logic

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/authentication#395]
### Steps to reproduce

1) Use following before hooks in _myservice_:
```
find: [
    auth.verifyOrRestrict(),
    auth.populateOrRestrict(),
    custom.myhook(),
  ],
```

```
exports.myhook= function () {
  return function (hook) {
    console.log("provider",hook.params.provider);
    if (hook.params.user || !hook.params.provider) {
       //restrict even more unless internal server call
    }
}}
```
2) Use browser to navigate to http://localhost:myport/myservice
### Expected behavior
Myservice should be called only once with the provider="rest"

### Actual behavior
Call will be made, but myhook **will be called twice**. First with `provider="rest"` (correct) and second with `provider=undefined` (wrong). The latter will undermine any security concept one is doing by utilizing the provider param.

The final output is the one from the second call.

_Logs will show:_
```
provider rest
provider undefined
```

### System configuration

**Module versions**:
"feathers-authentication": "^0.7.12",
"feathers": "^2.0.2",
"feathers-rest": "^1.6.0",
"feathers-sequelize": "^1.4.0"

**NodeJS version**: 7.4.0

**Operating System**: win10

**Browser Version**: ALL

**Comment by eikaramba** [comment]
I know that with the new authentication and permission plugins this issue might be gone, however currently this was a big issue for me. Especially as i first thought that browser calls and internal calls are the same as both was showing up with provider=undefined. just after some debugging i learned that i can safely assume if provider=undefined, that this must be an internal call and thus i do not restrict anything. However this is not true if one is using one of the xxxOrRestrict hooks.

**Comment by eikaramba** [comment]
Another reason why this is especially bad for me is, because verifyOrRestrict does not pass along the sequelize parameter. In my custom hook i'm restricting access by modifying the sequelize object. Normally that works good, however here this parameter is not passed along and thus, my whole restriction concept falls apart :(

**Comment by eikaramba** [comment]
for everyone that has the same use case as me:
Having a Service which is:

1. accessible without any form of authentication --> public entries
2. accessible with authentication but restricted if user is not special --> public & special entries
3. accessible via internal call without any restrictions --> everything

I copied the code from verify and populate hooks and just customized my hook:

exports.myhook= function (options) {
  return function (hook) {
    if(!hook.params.token){
      if(hook.params.provider) {
        hook.params.query = hook.params.query || {};
        //only called when no authentication and not internal call --> e.g. case 1)
      }
   //code for case 3
    }else{
      var token = hook.params.token;
      var authOptions = hook.app.get('auth') || {};
      var options = Object.assign({}, authOptions, authOptions.token);
      var secret = options.secret;
      if (options.algorithm) {
        options.algorithms = [options.algorithm];
        delete options.algorithm;
      }
      return new Promise(function (resolve, reject) {
          jsonwebtoken.verify(token, secret, options, (error, payload) => {
            if (error) {
              return reject();
            }
            hook.params.payload = payload;
            return hook.app.service('users').get(hook.params.payload['id']).then(user => {
              hook.params.user = user;
              ////code for case 2
              return resolve(hook);
            }).catch(function () {
              return reject();
            })
          })
        })
    }
  };
};

**Comment by eikaramba** [comment]
I just converted everything to AUK Release with latest authentication version. Unfortunately the approach from above does not work anymore (there is no `hook.params.token` anymore). **How can i do different things depending whether the user is authenticated (user object must be attached to params) or not?**

**Comment by daffl** [comment]
The `orRestrict` hooks have now been deprecated. [feathers-authentication-hooks](https://github.com/feathersjs-ecosystem/feathers-authentication-hooks) now only contains `queryWithCurrentUser` and `restrictToOwner`.

Role based permissions can be achieved through [feathers-permissions](https://github.com/feathersjs-ecosystem/feathers-permissions), conditional restrictions should be implemented in your own conditional hooks (useful: [feathers-hooks-common#iff](https://feathers-plus.github.io/v1/feathers-hooks-common/#iff)).
