### ISSUE TITLE
Associate multiple authentication strategies with 1 user

### ISSUE THREAD

**Issue by bcojan** [feathersjs/authentication#402]
### Steps to reproduce
Is it Possible to use multiple authentication strategies for 1 user?
I'm building an app where I need to connect one user to serval services like Github, Bitbucket, ... 
Ideally, the user could log with any service, and add additional services later on. 

### Expected behavior
I would like to be able to send a user identifier along with the oauth call in order to tell feathers to associate an existing user with a new oauth provider. 

### Actual behavior
For the moment, feathers-authentication seems to create a new user for each oauth Strategy I'm using.

**Comment by daffl** [comment]
With cookies enabled and the existing JWT set as `feathers-jwt` in the cookie, account linking is now possible with `@feathersjs/authentication-jwt@^2.0.0` and `@feathersjs/authentication-oauth@^1.2.0`.
