### ISSUE TITLE
Be careful with discard('password') in user

### ISSUE THREAD

**Issue by MHerszak** [feathersjs/authentication#434]
I just realized I was adding `discard('password')` to after find hook for my `users` model. I got the `Error: 'user' record in the database is missing a 'password'`. Maybe just add a little reminder to be careful with `discard('password')` when it is actually necessary for `checkCredentials` for `local` authentication.

**Comment by daffl** [comment]
@eddyystop I know we talked about that it is pretty easy to make this conditional using `commonHooks.when` but I'm still wondering if it should only discard when a provider is set. This is the third or fourth time I've seen this problem come up.

**Comment by eddyystop** [comment]
There is a reason we wanted to remove the "magic" from inside some hooks. For example, more than once we've had people on Slack surprised that `remove` did not remove anything when called from on the server.

A name like `discard` should just discard, while it looks reasonable for a name like `discardForExternal` to be conditional.

**Comment by ekryski** [comment]
@MHerszak makes a fair point, it is easy but it's also pretty apparent as to what the error is.

I don't think we should do anything other than maybe have a warning or log inside the hook. It should be consistent with the rest of the hooks and not assume the existence of a provider, otherwise we'd be repeating the mistake of `remove` (which in my opinion we should have just updated as part of v3.0.0 instead of adding yet another hook that appears to do the same thing).

**Comment by MHerszak** [comment]
Yeah, this is not simple. A quick fix would be to set `this.options.passwordField` to `null` but that would probably add other problems.

**Comment by snewell92** [comment]
I created a symbol that I check for now.

```
export const AuthMode = Symbol('AUTH');
```

I use it as a property on the hook params, set it to a boolean. Then I can disable it after the authentication hook if I need default behavior for whatever reason.

```

const setAuthMode = hook => hook.params[AuthMode] = true;
const disableAuthMode = hook => hook.params[AuthMode] = false;
/* ... */

before: {
  create: [
    setAuthMode,
    authentication.hook.authenticate(config.strategies),
    disableAuthMode,
    populateUserPayload
  ], /* ...*/
}

```

There could be an internal symbol feathers uses, and then common hooks (like discard) could switch behavior based on the needs of other internal services based on either the presence of the symbol property, or the symbol property's value. That wouldn't interfere with those hooks' general behaviors, while still working seamlessly all together.

And the above authentication service hook example could be the output of the CLI, to be more explicit, or the authentication hook could set that param before it calls whatever is set as the user service.

**Comment by daffl** [comment]
I like the idea using Symbols. The [next version of Feathers](https://blog.feathersjs.com/after-auk-whats-next-for-feathers-buzzard-c68358a3e62f) will also allow hooks to set the `dispatch` data which is what providers will use so hopefully some of those issues should be preventable.

**Comment by daffl** [comment]
This has been fixed via the [protect hook](https://docs.feathersjs.com/api/authentication/local.html#protect).
