### ISSUE TITLE
Test for controlling socket auth through params.authenticated

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/authentication#463]
We need to add a test for preventing socket auth.

```js
app.service('authentication').hooks({
  before: {
    create: [
        function (hook) {
          hook.params.authenticated = false;
        },
        auth.hooks.authenticate(['some-custom-strategy'])
    ]
  }
})
```

**Comment by ekryski** [comment]
I don't know what this means ha ha. Can you elaborate @marshallswain?

**Comment by daffl** [comment]
I don't get it either. Has this something to do (or possibly fixed) with #459?

**Comment by marshallswain** [comment]
Yeah.  This is fixed in that PR, I just forgot to add docs.  You can now set `hook.params.authenticated` to `false` if you want to return a successful auth response, but not authenticate the socket client.  This should go into the docs on how to create custom providers / how to customize the existing providers.

**Comment by marshallswain** [comment]
Docs are done.  Just needs a test, now.
