### ISSUE TITLE
rename `app.authenticate()` to `app._authenticate()`

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/authentication#468]
The `authenticate` method is only useful on the server for transport plugin developers.  We are going to rename it to `_authenticate` to remove any confusion that it should be used for authentication in general.  See https://github.com/feathersjs/feathers-authentication/issues/466#issuecomment-290789550 for more information

**Comment by daffl** [comment]
Does it have to be on `app` at all? It's just an alias for `app.passport.authenticate` right?

**Comment by marshallswain** [comment]
Yep, and it sets passport as the context, but that's all.

**Comment by daffl** [comment]
Either change could be breaking so we might as well remove it.

**Comment by ekryski** [comment]
no I want to keep it, it should just be a private method. It is an alias for `app.passport.authenticate` but it calls it with `passport` as the context. This method is only used if you are writing another transport adapter (which we may do in the future).
