### ISSUE TITLE
Authenticate should check that client provided strategy is valid

### ISSUE THREAD

**Issue by hubgit** [feathersjs/authentication#472]
[The README for the `authenticate` hook](https://github.com/feathersjs/feathers-authentication/tree/master#hooks) says that "You can chain multiple strategies" (by passing an array)  but [in the code](https://github.com/feathersjs/feathers-authentication/blob/master/src/hooks/authenticate.js#L25) it only uses the first value of the array (and even ignores that if `hook.data.strategy` is set).

It seems that the array passed into the hook is meant to limit the strategies that can be used, but that doesn't seem to be happening, unless I'm missing something.

**Comment by sylvainlap** [comment]
I agree with @hubgit.

I change my authentication config to set only the 'jwt' strategy:
```
app.service('authentication').hooks({
    before: {
      create: [
        authentication.hooks.authenticate('jwt'),
      ],
    },
  });
```

and I am still able to get an accessToken thanks to this payload:

```
{
	"strategy": "local",
	"email": "john.doe@gmail.com",
	"password": "passw0rd"
}
```

**Comment by daffl** [comment]
You do but it's not going to contain any useful information (as in it will be anonymous). I agree that it should error in that case as well. The related issue is #392

**Comment by Mattchewone** [comment]
There seems to be an issue with the fact that you can pass an array of strategies but only the first one is used. Is there a reason why you allow for an array but only use the first item? 

```
      if (Array.isArray(strategies)) {
        strategy = strategies[0];
      } else {
        strategy = strategies;
      }
```

When "local" strategy is first, this allows for credentials to be used to create a token, an not allowing anonymous tokens, but using the "jwt" option first allows for anonymous but does not allow credentials to be used.

**Comment by ekryski** [comment]
The short answer is, "it's complicated".

You're only looking at one part of the authentication. Yes, the code you are pointing to it does not matter. What we are doing there is if you didn't provide a `strategy` when you try to authenticate with the server, we just grab the first one that has been registered server side and assume that is the one you are trying to auth with. Not ideal but it's not likely to happen because `feathers-authentication-client` forces you to provide one.

Although looking at this again with fresh eyes I think we should just force the `strategy` option from the client and I can update this to support arrays a bit better.

**Comment by daffl** [comment]
I think we talked about doing this before. Totally makes sense to force the `strategy` in order to avoid any ambiguity.

**Comment by hubgit** [comment]
Note that if the strategy is forced (which makes sense) there's still a bug here, as it's not actually validating that the strategy from the client is in the server's array of allowed strategies.

**Comment by huggler** [comment]
Hi guys, I receive the message...

error: NotAuthenticated: Invalid login
    at new NotAuthenticated (C:\Projetos\SkeewsMe\node_modules\@feathersjs\errors\lib\index.js:93:17)
    at app.authenticate.then (C:\Projetos\SkeewsMe\node_modules\@feathersjs\authentication\lib\hooks\authenticate.js:76:31)
    at <anonymous>

I using 
    "@feathersjs/authentication": "^2.1.7",
    "@feathersjs/authentication-jwt": "^2.0.1",
    "@feathersjs/authentication-local": "^1.2.1",
    "@feathersjs/authentication-oauth2": "^1.1.0",

i my user hooks

module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [local.hooks.hashPassword({ passwordField: 'password' })],

thanks for help me

**Comment by daffl** [comment]
Since https://github.com/feathersjs/authentication/pull/663, the `strategy` is now being verified against the list registered in the hook.
