### ISSUE TITLE
jwt cookie is not set after the correct authentication

### ISSUE THREAD

**Issue by PavelPolyakov** [feathersjs/authentication#514]
### Steps to reproduce

https://github.com/PavelPolyakov/feathers-authentication-cookie-bug

The reproduction repo is based on the simple generated app. The only thing to highlight is that I've packed https://github.com/feathersjs/feathers-authentication-client and put it as `auth.bundle.js`, as it's not possible to include it from the CDN.

In order to reproduce:
1. run the app
2. visit the index page, check in the console that we logged in
3. check in the developer tools, that there is no `feathers-jwt` cookie
4. in case you need a clean test - restart the app

### Expected behavior
It is stated in the documentation:
https://docs.feathersjs.com/api/authentication/server.html#default-options

That in case we enable `cookie`, then the appropriate cookie would be set after the successful authentication.

### Actual behavior
The cookie is not there.

### System configuration
nothing special

**Module versions** (especially the part that's not working):
`feathers-client 2.2.0`
`feathers-authentication-client 0.3.2`

**NodeJS version**:
`v6.3.1`

**Operating System**:
`Mac OS`

**Browser Version**:
`latest Chrome`

**React Native Version**:
--

**Module Loader**:
--

Please, let me know if it's a bug. Seems that the same behaviour is mentioned here: https://github.com/feathersjs/feathers-authentication/issues/389 , however, there the main topic is `react native`.

Regards,

**Comment by snewell92** [comment]
While using the feather's client, I've got authentication working and even storing the token in localStorage, but it doesn't set the cookie. Thus subsequent redirects won't be authenticated.

I've looked at trying to have [middleware set the cookie](https://github.com/feathersjs/feathers/issues/385#issuecomment-238592552) but I don't think that works anymore, and I don't want to expose cookies to all my hooks, I just would like the authentication after hook to set the `jwt-cookie` cookie value so my express routes can authenticate with an http only cookie.

**Comment by snewell92** [comment]
In the chrome debug inspector, after the client authenticate I get this response back

![setcookieheaderset](https://user-images.githubusercontent.com/25957964/28028039-e3da13c0-6560-11e7-8448-c3bff84afad3.JPG)

This is in the `then` right after I authenticate. So... does the server assume it can defer setting the cookie on the client? Even though it is an http only cookie? (which can't be set by the client)

**Comment by snewell92** [comment]
It's worth noting too, that `localStorage` works as expected. In my client I set localStorage, but I still am expecting the cookie to be set, since the server still has the cookie options enabled.

**Comment by snewell92** [comment]
This is odd... I see two set-cookies, and in the cookies tab there are two jwt-cookies...
![twocookies](https://user-images.githubusercontent.com/25957964/28035937-fc77fc88-657b-11e7-8978-dc21f2f115b1.JPG)

**Comment by snewell92** [comment]
Well, for my issue I think `res.clearCookie` is adding that blank cookie. I put console log statements in `set-cookies.js` and printed out `res._headers` before clear cookie, after clear cookie, and after res.cookie invocations.

**Comment by kernwig** [comment]
Suddenly I'm running into this too with feathers 2.2.0 / feathers-client 2.4.0.

![image](https://user-images.githubusercontent.com/25376618/34919375-9a70f99c-f917-11e7-8636-24039ce2ed4f.png)

**Comment by metamas** [comment]
I set up a protected route as outline in docs.feathersjs.com/guides/auth/recipe.express-middleware.html, and am experiencing the say lack of cookie storage. Auth flow with `localStorage` still works fine, but even with that present on the client a user can't access the protected route when there is no `feathers-jwt` cookie to parse.

**Comment by roemhildtg** [comment]
I am also seeing duplicate Set-Cookie headers. One is empty, so is it possible that this is interfering with the cookie that is set? Chrome doesn't show a cookie in Application -> Cookies. 

Version info:
```
    "@feathersjs/authentication": "^2.1.3",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.1",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.0",
    "@feathersjs/feathers": "^3.1.3",
```

**Comment by Sebi55** [comment]
I experienced the same problem.
I was using isomorphic-unfetch as fetch client.

```
const fetch = require('isomorphic-unfetch');
const app = feathers(); 
 
export default app 
  .configure(rest().fetch(fetch))  
```

I switched to axios and the cookie was saved without any problems.

```
const axios = require('axios');
const app = feathers();

export default app
  .configure(rest().axios(axios))
```

**Comment by artbelikov** [comment]
Same here. Two Set-Cookie headers. One is normal and one is empty.

**Comment by rxb** [comment]
Did anyone ever discover any workarounds for this?

**Comment by rxb** [comment]
Did anyone discover any workarounds in the meantime?

**Comment by r3gisc** [comment]
I had a similar issue: cookie for feathers-jwt was in the Header _(even 2 of it: one is perhaps set to clear the other - see @feathers/authentication/lib/express/set-cookie)_, but none was stored in the browser on production ... But it was working for me ... on dev server only !

**Finaly i found the problem came from cookie's domain (to be precise: subdomain) set by feathers/auth**

On dev server everything was fine because node and front server was sharing the exact same domain:
_front: sub.domain.com:443
node: sub.domain.com:8443_

But in production subdomains were differents:
_front: app.domain.com:443
node: srv.domain.com:8443_

@feathers/authentication may have set the cookie's domain to `srv.domain.com` or none (not totally sure).

**My theory is that app.domain.com was then not allowed by the browser to store it.**

Anyway, after trying different workarounds if found the simplest ... that is not documented in feathers doc : 

**Add a `'domain'` option in node config for authentication.cookie key:**

```    
     authentication:{
            cookie: {
                enabled: true,
                name: conf.cookies.auth,
                httpOnly: false,
                secure: true,
                domain: 'domain.com'  // <====  
                     // or domain: 'app.domain.com' in my case 
                     // (i had issues with config loader and "dot" '.domain.com')
                     // this option is not documented but is passed trough to res.cookie(
            },
       }
```

**Comment by daffl** [comment]
oAuth has been changed significantly in Feathers v4 authentication and does no loner use cookies to transmit the token.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
