### ISSUE TITLE
Authentication with server-side rendering

### ISSUE THREAD

**Issue by jarnojellesma** [feathersjs/authentication#560]
### Steps to reproduce

https://github.com/jarnojellesma/feathersjs-nuxt-server-rendered

### Expected behavior
User should be authenticated on page refresh.

### Actual behavior
The user is not authenticated when the page is refreshed. This is because the first request is rendered on the server, because of this I'm receiving "window is not defined" errors.

### System configuration
I am using Nuxt (Vue) on the front-end for server rendering the first request.

**Module versions**:
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.6",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-client": "^2.3.0",

**Comment by daffl** [comment]
There is now a recipe showing how to use Feathers authentication with Express middleware (including server side rendering) at https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html
