### ISSUE TITLE
Grant access with facebook token (without user interaction)

### ISSUE THREAD

**Issue by srdjanarsic** [feathersjs/authentication#561]
Hi,

I'm using using ionic and cordova auth plugin for native facebook authentication . 
Authentication is fully accomplished on the client side and we have facebook access token. Next steps are:

1. send access token to server
2.  and validate it trough facebook api.
3. if validation pass, set user as "logged in", otherwise set error. 

As i'm new to feathersjs, i'm not sure how to implement this (1 and 3) with feathersjs.
I suppose this is a common scenario for native apps which use feathers as backend, so this will be very interesting for many developers  :)

Thanks.

**Comment by vinaybedre** [comment]
Can someone help here?

**Comment by evilchis94** [comment]
@srdjanarsic You must configure your authentication in backend with [passport-facebook-token](https://github.com/drudge/passport-facebook-token), then in client add facebook accessToken in your params when login, 

`{ 
                strategy: 'facebook',
                access_token: token.accessToken 
            }`

**Comment by morenoh149** [comment]
@evilchis94 I'm struggling with this at the moment. I have a minimal example at https://github.com/morenoh149/feathers-chat-facebook-signup-api that errors when I POST /authentication

Are you simply supposed to post to the authentication endpoint or are you expected to create the user first?
