### ISSUE TITLE
Feathers.authenticate gives window undefined (server-rendered)

### ISSUE THREAD

**Issue by jarnojellesma** [feathersjs/authentication#573]
### Expected behavior
`feathersClient.authenticate({ strategy: 'jwt', accessToken })` should authenticate the user, the accessToken is a valid token which I'm taking from the "req" object (server rendered).

### Actual behavior
```
ReferenceError: window is not defined
    at Object.setItem (src/client/helpers/ssr-storage.js:13:4)
    at Passport.setJWT (/current/CURRENT/PROJECT/node_modules/feathers-authentication-client/lib/passport.js:282:33)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

I receive a window is not defined error, but I am rendering server-side (NuxtJs / Vue)

**Module versions** (especially the part that's not working):
    "feathers": "^2.1.1",
    "feathers-authentication": "^1.2.6",
    "feathers-authentication-hooks": "^0.1.4",
    "feathers-authentication-jwt": "^0.3.1",
    "feathers-authentication-local": "^0.4.3",

**Comment by marshallswain** [comment]
@jarnojellesma I don't think feathers-authentication-client uses `window`, at all.  This might be happening because you're passing a `storage` option that does use `window`.

**Comment by andysay** [comment]
up, how fix it?

**Comment by marshallswain** [comment]
@andysay if you're going to build a server side rendered app, you have two options to fix this:

1. Don't use `window` anywhere in your code.
2. Shim `window` and `window.localStorage` on the server.

**Comment by andysay** [comment]
```
  return feathersClient.authenticate({ strategy: 'jwt', accessToken })
      .then((response) => {

        return feathersClient.passport.verifyJWT(response.accessToken);
      })
      .then(payload => (
         feathersClient.service('users').get(payload.id)
      ))
      .then(user => {
        feathersClient.set('user', user);
       console.log('User', feathersClient.get('user'));
      });


```
its Example like doc , but if i refresh webpage ReferenceError: window is not defined

but i not use window anywhere

**Comment by marshallswain** [comment]
@andysay Do you have a stack trace for the error?  Next step is to find the line of code causing the error.  

Also, the `window.localStorage` would be in the feathers client setup, usually, if that were the problem.

**Comment by andysay** [comment]
@marshallswain i found               token = window.localStorage.getItem(cookieName);
what to replace this ?

**Comment by marshallswain** [comment]
@andysay where did you find that?

**Comment by andysay** [comment]
@marshallswain in client side

**Comment by marshallswain** [comment]
@andysay If you want my help, you'll need to provide more information.  Otherwise, you'll just have to figure it out.

**Comment by andysay** [comment]
@marshallswain 

`/* eslint-disable */
const cookieName = 'feathers-jwt';

function getTokenFromRequest(req) {
  if (!req || !req.headers || !req.headers.cookie) return undefined;
  const jwtCookie = req.headers.cookie.split(';').find(c => c.trim().startsWith(`${cookieName}=`));
  if (!jwtCookie) return undefined;
  return jwtCookie.split('=')[1];
}

export default function ({ isServer, store, req }) {
  const accessToken = (isServer) ? getTokenFromRequest(req) :
    window.localStorage.getItem(cookieName);

  if (!accessToken) return undefined;

  return store.dispatch('auth/jwt', { accessToken })
    .then(() => { console.log('success'); })
    .catch((error) => {
      console.log(error);
      // Ignore invalid JWT
    });
}
`

its my middleware check-auth on client side 

server response ReferenceError: window is not defined
 thanks

**Comment by marshallswain** [comment]
Check your Feathers client setup.
