### ISSUE TITLE
JWT Cookie is unwillfully deleted in error handler when connecting an OAuth account to an existing user

### ISSUE THREAD

**Issue by Avnerus** [feathersjs/authentication#602]
Hi,
As mentioned [here](https://github.com/feathersjs/authentication-oauth1/issues/34),
I am using a custom JWT authentication with cookies for my users, but also allowing them to "connect" their twitter/facebook accounts via OAuth1/2.
If the users clicks to connect their facebook account for example, but then press "Cancel", it activates the error handler and `failureRedirect`. I just want them to go back to screen they came from.
However, because of [this](https://github.com/feathersjs/authentication/blob/master/lib/express/failure-redirect.js#L10) line, the error handler deletes their JWT cookie and they are no longer authenticated on my site.
Am I doing something wrong? I had to comment out this line for it to work.
Thanks!

**Comment by daffl** [comment]
With cookies enabled and the existing JWT set as `feathers-jwt` in the cookie, account linking is now possible with `@feathersjs/authentication-jwt@^2.0.0` and `@feathersjs/authentication-oauth@^1.2.0`.
