### ISSUE TITLE
Allow custom authentication service registration

### ISSUE THREAD

**Issue by thomas-p-wilson** [feathersjs/authentication#609]
Pursuant to https://github.com/feathersjs/authentication/blob/master/lib/index.js#L52, permit the developer to provide their own authentication service.

**Comment by thomas-p-wilson** [comment]
I haz a PR incoming for this.

**Comment by subodhpareek18** [comment]
Not sure why this needs a PR, custom auth strategies area already possible.
https://docs.feathersjs.com/guides/auth/recipe.custom-auth-strategy.html

**Comment by daffl** [comment]
Thank you for the PR @thomas-p-wilson. My question is, is this code change necessary if we could just set `hook.result` in a `before` hook for the existing `authentication` service (which will skip the built in service call)?

**Comment by thomas-p-wilson** [comment]
@subodhpareek18 this requires a PR because custom authentication services are outside the scope of custom auth strategies. A strategy and the service which underpins them are not the same. I implemented it both because it served my purpose, as well as because there was a code comment which suggest it be done!

@daffl I did not consider your suggestion beforehand. I will do so.

**Comment by subodhpareek18** [comment]
Ok can you share an example of a custom auth service which would implement a use case that a custom auth strategy can't.

**Comment by thomas-p-wilson** [comment]
I want to leverage the ease of authentication by using feathers-authentication, but I don't want a JWT. Simple as that. Perhaps more importantly though is why this is such an issue, given that this was already the intention according to the existing source code itself, found on https://github.com/feathersjs/authentication/blob/master/lib/index.js#L52. Quote:
> // TODO (EK): Support passing your own service or force
> // developer to register it themselves.

This isn't just me randomly coming up with an idea. This is me implementing an idea that someone already had and that I found useful for my purpose.

**Comment by DesignByOnyx** [comment]
Another thing to consider is the [feathers-authentication-custom](https://www.npmjs.com/package/feathers-authentication-custom) strategy where you can implement your own custom logic.

**Comment by daffl** [comment]
This has been done in Feathers v4 authentication.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
