### ISSUE TITLE
Server to Server Authentication Question

### ISSUE THREAD

**Issue by gwlava** [feathersjs/authentication#612]
Hi,

I've just recently started using FeathersJS and am prototyping a new system.

I've got 2 NodeJS server applications running, one performs the role of Feathers API Server (communicates to db, REST) and the other implements the Feathers client (my client Service) for making requests to the API service.

I want to have security implemented from my client Service to API service and have looked at the Custom Recipe in the documentation for using an API Key, I would be happy enough to use that but how do I send the key in the header for service methods from the feathers client?  

Is using an API key the best method to authenticate for my server to server scenario? 

Thanks

**Comment by daffl** [comment]
It sounds like the best way in this case. The [custom authentication strategy guide](https://docs.feathersjs.com/guides/auth/recipe.custom-auth-strategy.html) looks for an `X-Api-Key` header. So as long as you send an `A-Api-Key: <my-api-key>` header it should work.
