### ISSUE TITLE
Deleted user successfully signs in using JWT

### ISSUE THREAD

**Issue by abhisekp** [feathersjs/authentication#615]
### Steps to reproduce

1. Create a user
2. Create a auth token
3. Delete the user
4. Create another user with the exact same details as the previous user (_probably doesn't matter_)
5. Try to authenticate with the previous auth token

### Expected behavior
The deleted user should not be able to access resources and should throw on authentication.

### Actual behavior
The deleted user is given an authorization token and the user object is filled with an empty object.

**Comment by daffl** [comment]
I'm not seeing how a token with the userId of a deleted user would not throw an error after trying to populate the entity.

**Comment by daffl** [comment]
As long as the id changes, it should still fail. There was a mistake in the authentication hooks of the latest application which has been fixed via https://github.com/feathersjs/generator-feathers/pull/325 so I'm going to close this.

**Comment by abhisekp** [comment]
Is the issue fixed i.e. a deleted user should not be populated with an empty object and should throw on authentication?
