### ISSUE TITLE
Express middleware not setCookie

### ISSUE THREAD

**Issue by edDimensi** [feathersjs/authentication#617]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [x] Tell us what broke. The more detailed the better.

I look https://github.com/feathersjs/authentication/blob/dd182da97c34a060198b2932800801da17dfc8f9/lib/express/authenticate.js#L27-L37
but i not see here logic for set cookie.
### Expected behavior
Tell us what should happen
```
  app.post('/login', auth.express.authenticate('local',{ 
    successRedirect: '/',
    failureRedirect: '/bad',
  }));
```
will set cookie
### Actual behavior
Tell us what happens instead
nothing happing, only redirect works.
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**: 9.3.0

**Operating System**: Arch

**Browser Version**: Chrome 63

**Comment by daffl** [comment]
There is now a recipe showing how to use Feathers authentication with Express middleware (including server side rendering) at https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html
