### ISSUE TITLE
cookie reused from server in SSR app

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/authentication#619]
### Steps to reproduce

I'm using NextJS for front-store app, and I have to use cookie as a storage so it will work on server side as well. I also have one simple hook that will check if customer logged in or not. 
```js
const accessToken = ctx && ctx.isServer ? ctx.req.universalCookies.get('feathers-jwt') : client.cookie.get('feathers-jwt');
  return login({ accessToken, strategy: 'jwt' })
```
When we first open page in  a browser it will use cookie from server, then during navigating within the app it will use cookie on client side.
the problem is when I', logging out `client.logout()`, and will refresh the page, it still uses cookie from server and for some reason JWT is still there

### Expected behavior
after logging out remove cookie it shouldn't be JWT in client and server

### Actual behavior
after logging out I still have JWT on server side

**Module versions** (especially the part that's not working):
"@feathersjs/authentication-client": "^1.0.1",
"@feathersjs/feathers": "^3.0.2",
"@feathersjs/rest-client": "^1.3.2",
"@feathersjs/socketio-client": "^1.0.1",

**NodeJS version**:
8.9.1

**Comment by sarkistlt** [comment]
actually the problem was that even if I'm passing `client.authenticate({ accessToken: undefined, strategy: 'jwt' })` it gets authorized for some reason.  quick workaround:
```js
const accessToken = ctx && ctx.isServer ? ctx.req.universalCookies.get('feathers-jwt') : client.cookie.get('feathers-jwt');

  return new Promise((resolve, reject) => {
    if (accessToken) {
      login({ accessToken, strategy: 'jwt' })(dispatch)
        .then(resolve)
        .catch(reject);
    } else {
      reject(new Error('not authorized'));
    }
  });
```
but still it's not a correct behavior, how it can get authorized without passing JWT or having it in a cookie?

**Comment by paulrostorp** [comment]
I am getting a similar problem working with with NUXT and feathers 3.
USER A logs in
USER B logs in (different client)
USER A refreshes page, logged in as user B ?!
Have not been able to get to the bottom of this but it definitely is a problematic behavior...

**Comment by daffl** [comment]
There is now a recipe showing how to use Feathers authentication with Express middleware (including server side rendering) at https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html
