### ISSUE TITLE
attach social to current user

### ISSUE THREAD

**Issue by mogadanez** [feathersjs/authentication#626]
In this scenario I need  access to currently logged user in   strategy  callback

```
passport.use(new SomeSocialStrategy({
    returnURL: 'http://localhost:3000/auth/social/callback',....
   passReqToCallback:true
  },
  function(req, profile, done) {
     ///?????    
    req.user.socialId = profile.id
   
  }
));
```

Is it right that its not possible  without enabling session/cookies?

**Comment by mogadanez** [comment]
I  use custom route  for callback  like in 
https://github.com/feathersjs/feathers/issues/672

```
app.get('/auth/SomeStrategy/callback',
  cookieParser(),
  (req,res,next)=>{
   // cookie extractor, put cookie to header.
   next();
  },
  authenticate('jwt'),
  authenticate('SomeStrategy'),
  function(req, res) {
       res.redirect(/)
  }
);
```

but https://github.com/feathersjs/authentication/blob/master/lib/express/authenticate.js#L14
prevents   second strategy  from executing

**Comment by daffl** [comment]
With cookies enabled and the existing JWT set as `feathers-jwt` in the cookie, account linking is now possible with `@feathersjs/authentication-jwt@^2.0.0` and `@feathersjs/authentication-oauth@^1.2.0`.
