### ISSUE TITLE
Socket.io and cookie.

### ISSUE THREAD

**Issue by mogadanez** [feathersjs/authentication#627]
Authentication via socket.io not set the cookies

can I setup rest transport on auth service only?

**Comment by daffl** [comment]
The token is stored in localStorage. Cookies are usually only used to transfer the token in an oAuth flow.

**Comment by mogadanez** [comment]
Yes its exactly my case.
But someone should setup this cookie.  I'd prefer to keep  cookie  **httpOnly**, so setting it manually on client side not an option.

Since all communication goes through sockets, no one call set-Cookie.  So when I going on **/auth/SomeOauth/** or  **/auth/SomeOpenid/**  it called without cookies => "unauthorized"

Another idea -  doing request for   **/auth/SomeOauth/:TOKEN**, where TOKEN is JWT token itself  or one time temporary  token requested exactly before opening

**Comment by TimNZ** [comment]
I'm starting to think that when using mixed auth, that after a REST or socket login, the cookie needs to be set on the server and the client redirected to an endpoint that loads the 'logged in' page so the browser is sent the cookie and manually updating the localStorage managed feathers-jwt value, to keep it in sync with the cookie feathers-jwt set from the oauth flow.

I'm having issues with them being out of sync and the client sdk using localStorage ver over the cookie which is newer, on client page load.

An issue with this approach will be if a user has been authenticated via cookie, /auth/<provider/callback strategy will not be executed as no further strategies are executed if req.authenticated, making it more challenging linking a new social login to a local user, as @mogadanez already discovered in this issue: https://github.com/feathersjs/authentication/issues/626

Would love guidance on best practice here to support mixed token and cookie usage.

This also ties into my thoughts on the need for sessions:
https://github.com/feathersjs/authentication/issues/569

**Comment by daffl** [comment]
I started following up on those issues with https://github.com/feathersjs/authentication-jwt/pull/55 which is part of both, adding strategies to the same user and doing server side rendering.

**Comment by musicformellons** [comment]
[This](https://stackoverflow.com/questions/49076781/feathersjs-oauth2-not-working) might be related?!

**Comment by daffl** [comment]
oAuth has been changed significantly in Feathers v4 authentication and does no loner use cookies to transmit the token.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
