### ISSUE TITLE
registered many authentication services

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/authentication#634]
Right now I'm getting error:

```cli
Error: You have already registered authentication on this app. You only need to do it once.
```

us it possible somehow register more then one? like so:
```js
  .configure(auth(app.get('auth')))
  .configure(auth(app.get('authCustomers')))
  .configure(auth(app.get('authAdmins')))
...
```
and each will have separate endpoint and service.

**Comment by daffl** [comment]
That is currently not possible. To me this looks like just different types of users which can be much easier handled by adding a `type` property to them.

If things are in different services I usually recommend to create an `entity` service for authentication that then links to the appropriate other service (`users`, `machines`, `customers`) through fields like `userId`, `machineId`, `customerId`.

**Comment by sarkistlt** [comment]
different types make sense, but what if those users in different tables in db. anyway I think `entity` service should solve this problem, thanks.
