### ISSUE TITLE
context.params.user is empty object

### ISSUE THREAD

**Issue by dengunya** [feathersjs/authentication#635]
Using **auth.hooks.authenticate(['jwt'])**
Trying to get current user from hook.
There is **context.params.user** but it's empty object.
Changing "entity" option works, still **context.params['entity']** is empty.
Am i doing something wrong ?

### Steps to reproduce
Use auth.hooks.authenticate(['jwt']) hook
Use own hook afterwards and try getting **context.params.user**

### Expected behavior
**context.params.user** populated with user object (or at least userId)

### Actual behavior
**context.params.user** is empty object

**Module versions** (especially the part that's not working):
    "@feathersjs/authentication": "^2.1.1",
    "@feathersjs/authentication-jwt": "^1.0.2",
    "@feathersjs/authentication-local": "^1.0.4",

**Comment by daffl** [comment]
What does [the encoded JWT](https://jwt.io/) you are sending look like? I'm suspecting it does not have a `userId`?

**Comment by dengunya** [comment]
> What does the encoded JWT you are sending look like?

Here's genetated token:
eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1MTg0MjU3NTgsImV4cCI6MTUxODUxMjE1OCwiYXVkIjoiaHR0cHM6Ly9kb21haW4uY29tIiwiaXNzIjoiZmVhdGhlcnMiLCJzdWIiOiJhbm9ueW1vdXMiLCJqdGkiOiIzNGYyNzYwOS0yM2FhLTQ0OWMtYWQ1NC1iMmM3OTU1MmMxM2UifQ.mN1lEoUck7vY0o1vnoimn6TaS6ujX7qhyjd1bVzMW-U

Seems there's no userId.

**Comment by dengunya** [comment]
The problem is that I don't call authentication service directly, but do smth. like:

  app.post('/users/authenticate', function (req, res, next) {
    app.service('/authentication').create({
      strategy: 'local',
      email: req.body.email,
      password: req.body.password
    }).then(token => {
        res.send(token);
    });
  });

because I need to avoid passing "strategy", just username and password and use another url.
And I wonder if I can pass User to params from Authentication After Create Hook.
