### ISSUE TITLE
Cannot limit authentication method per service

### ISSUE THREAD

**Issue by andreesteve** [feathersjs/authentication#639]
I am a bit confused how to properly use the authenticate hook. From the docs it seems that it can be used to limit what kinds of authentication methods are accepted per service. Like in this [example](https://docs.feathersjs.com/api/authentication/local.html#configuration) where it does:

```js
// Setup a hook to only allow valid JWTs or successful 
// local auth to authenticate and get new JWT access tokens
app.service('authentication').hooks({
  before: {
    create: [
      authentication.hooks.authenticate(['local', 'jwt'])
    ]
  }
});
```

I may have misunderstood it, but the way I made sense of it was that the authentication service would only accept *local* **OR** *jwt* authentication methods, but not anything else.

In my case, I want a specific service to only be authenticated by a specific method (say *jwt*), despite my application being able to support other types (e.g. *local*). The real use case is that I don't want JWT tokens to be use to get new JWT tokens. But I don't want any other service but the authentication service to accept username/password (i.e. *local* authentication method).

I noticed that the caller can actually pick the authentication method by passing the *strategy* property in the *hooks.data* - for instance, when using REST, that means POSTing with body containing { "strategy": "someValue" }. If the goal of the authenticate hook is to pick the allowed authentication methods, then I believe this would be a security bug.

I do see how letting the client pick the authentication method under the authentication service is desirable, but it seems that the service should be able to restrict the possible authentication methods used, despite having many configured in the application.

### Steps to reproduce

I have tried it on this [sample code](https://runkit.com/embed/4oul93fsixdp). It creates a service 'test' with 

```js
app.service('test').hooks({
   before: {
      all: [ auth.hooks.authenticate('jwt') ]
   }
});
```
So my expectation was that only access tokens would be accepted, but a client was able to successfully POST to it without an access token by issuing the following request:

```js
const clientTest = clientApp.service('test');
await clientTest.create({ 'prop': 'value', 'strategy': 'local', 'email': 'a@a.com', password: '1' });
```

### Expected behavior
Add the authenticate hook to a service to limit the authentication method to be 'JWT'. The client could only call it with an access token.

### Actual behavior

A client can POST to the service with { 'strategy': 'local' } and change the authentication method the service uses to authenticate, which seems to be due to how the strategy is selected [here](https://github.com/feathersjs/authentication/blob/a23e16abdbe786d8c49e6a86726c72427d2bf608/lib/hooks/authenticate.js#L25). This also seems to also ignore anything but the first value in the array, in case the client didn't pick the method.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

@feathersjs/authentication 2.1.2

**NodeJS version**:

8

**Operating System**:
**Browser Version**:
**React Native Version**:
**Module Loader**:
N/A

**Comment by daffl** [comment]
Your sample code is running _on the server_. Feathers authentication is only used for _authenticating external requests_ (through one of Feathers supported transports).

There is no reason to authenticate anything on the server since it can run everything anyway. If you need a user you can just pass it as shown in the [chat application testing guide](https://docs.feathersjs.com/guides/chat/testing.html).

**Comment by andreesteve** [comment]
Hi @daffl , thanks for looking at this. 

Although the sample code runs in the same process as the server, it makes an HTTP request (using REST) to the port feathers server listens to. From the feathers server instance, it should treat it as an external request, I believe. 

The client code is in the very bottom of the sample code - it creates a feather client, associate it with the feathers-REST client and makes the call.

To test it that this client instance **can** trigger an authentication failure, I've added an explicit call to check whether if I remove the *password" from the body I get HTTP 401, and I do:

```js
// showing that server returns 401 when no auth is provided
try
{
     await clientTest.create({ 'prop': 'value' });
 }
 catch (e)
 {
    console.log(e);
 }
```

I've updated the sample with the snippet here: [https://runkit.com/andreesteve/cannot-limit-authentication-method-per-service](https://runkit.com/andreesteve/cannot-limit-authentication-method-per-service).

Do you think you could take a quick look and give me your thoughts? Thanks!

**Comment by daffl** [comment]
Oops, sorry about that. I'll copy your code and look into it again.

**Comment by daffl** [comment]
I'm going to close this since Feathers v4 authentication has changed significantly enough to probably solve this issue (the authentication service no longer requires any hooks to be registered).

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
