### ISSUE TITLE
SameSite cookie option

### ISSUE THREAD

**Issue by ShimShamSam** [feathersjs/authentication#640]
Any chance support could be added for the SameSite cookie attribute?

Info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies
CanIUse: https://caniuse.com/#feat=same-site-cookie-attribute

**Comment by daffl** [comment]
This is already [supported by Express](http://expressjs.com/en/4x/api.html#res.cookie). Looks like adding `res.cookie('sameSite', true)` in a middleware should do it (see https://docs.feathersjs.com/api/express.html#custom-service-middleware for more information how to use custom middleware with services).

**Comment by ShimShamSam** [comment]
It's odd then that this library has built-in support for the Secure and HTTPOnly flags but not SameSite

**Comment by daffl** [comment]
Have you tried just setting `"sameSite": true` in the cookie configuration?

**Comment by daffl** [comment]
I'm going to close this since it should work by setting `"sameSite": true` in the authentication cookie options. Please reopen if it does not.
