### ISSUE TITLE
Redirect middleware packaged in `@feathersjs/authentication/lib/express` is mysterious and maybe unnecessary

### ISSUE THREAD

**Issue by metamas** [feathersjs/authentication#648]
I had created a custom route inside my apps `/middleware/index.js`, and set it up as a protected route as explained in [authenticating express middleware recipe](https://docs.feathersjs.com/guides/auth/recipe.express-middleware.html):

```javascript
const cookieParser = require('cookie-parser');
const { authenticate } = require('@feathersjs/authentication').express;

module.exports = function (app) {
  app.set('view engine', 'pug');
  app.get('/submit', cookieParser(), autheticate('jwt'), (req, res) => res.render('submit'));
};
```

I wanted to change the default behavior from `authenticate()` rendering the provided 401 Error page to unauthenticated users that tried to access `/submit`, instead to redirect them to the `/login` route.

The [recipe briefly mentions](https://docs.feathersjs.com/api/authentication/server.html#express-middleware) additional `failureRedirect` middleware to do this, and also an inverse `successRedirect` middleware. Both are located with `authenticate()` inside `@feathersjs/authentication/lib/express`. However, beyond that there is little guidance of how to use them.

After, some frustration and no success trying to get the `failureRedirect` to work, another developer helpfully referred me to [Passports `authenticate()` documentation](http://www.passportjs.org/docs/authenticate). That's when the lightbulb 💡 went off that Feathers' `authenticate()` middleware is also Passport's, and so accepts the same options!

All I ended up having to do was add an options object with a `failureRedirect` property:

```javascript
app.get('/submit', cookieParser(), autheticate('jwt', { failureRedirect: '/login' }), (req, res) => res.render('submit'));
```

Likewise, for anyone wanting to pass a `successRedirect`.

This has left me wondering if the `failure-redirect.js` and `success-redirect.js` middleware packaged inside `@feathersjs/authentication/lib/express` are even necessary… or how they were intended to work in the first place 🤔

Can anyone explain how to use those middleware, and also clarify if in fact they are superfluous? 

**module version**: `"@feathersjs/authentication": "^2.1.1"`

**Comment by Jaden-Giordano** [comment]
Added a snippet to feathersjs/docs#1099 for an example that highlights this issue and how it could be used. Thanks again for creating the issue @metamas!

**Comment by daffl** [comment]
oAuth has been changed significantly in Feathers v4 authentication including a better and more easily customizable redirect mechanism.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
