### ISSUE TITLE
Safari and iOS facebook login can't redirect back, but others can.

### ISSUE THREAD

**Issue by Steven0811** [feathersjs/authentication#651]
I'm use Nuxt + feathers, and I want trying Facebook login feature by feathers authentication, and It's works on Chrome and Firefox not any problem, but only Safari and iOS's Safari, when server direct the Safari to Facebook , Facebook asks me to continue next step, just stuck in here, nothing happened, and stay same "continue page", iOS version show up an error was occurred, It's seems redirect or something wrong, when error occurred, I trying refresh my website that have been login, but just can't back to my redirect page.

Sorry for my bad English.

<img width="674" alt="screen shot 2018-03-16 at 7 13 32 pm" src="https://user-images.githubusercontent.com/4948562/37518005-5fb4c9b6-294e-11e8-9941-cebf3ce1c55b.png">

stuck in here, press 'OK' nothing happened.

![img_1258](https://user-images.githubusercontent.com/4948562/37518020-6dadac4a-294e-11e8-8595-08d550c535ec.png)

and iOS error.

![image](https://user-images.githubusercontent.com/4948562/37518632-f0a0cc02-2950-11e8-819f-e4bb01a5b9ad.png)

flash an error in millisecond.
```
// authentication.js

  app.configure(authentication(config));
  app.configure(jwt());
  app.configure(local());

  config.facebook.successRedirect = 'back';
  config.facebook.failureRedirect = 'back';

  app.configure(oauth2(Object.assign(
    {
      name: 'facebook',
      Strategy: FacebookStrategy,
    },
    config.facebook,
  )));

```

```
    "facebook": {
      "clientID": "myclientID",
      "clientSecret": "myclientSecret",
      "scope": [
        "public_profile",
        "email"
      ],
      "profileFields": [
        "id",
        "displayName",
        "first_name",
        "last_name",
        "email",
        "gender",
        "profileUrl",
        "birthday",
        "picture",
        "permissions"
      ]
    },
    "cookie": {
      "enabled": true,
      "name": "feathers-jwt",
      "httpOnly": false,
      "secure": false
    }
```
### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
 "@feathersjs/authentication": "^2.1.1"
**NodeJS version**:
8.9.4
**Operating System**:
macOS 10.13.3 (Server Environment : ubuntu 14.04 )
**Browser Version**:
Safari Version 11.1 (13605.1.33.1.2)

**Comment by daffl** [comment]
Can you try if this works with a plain [passport-oauth](https://github.com/jaredhanson/passport-oauth2) + Express setup?
