### ISSUE TITLE
feathersjs Invalid token: expired

### ISSUE THREAD

**Issue by andysay** [feathersjs/authentication#661]
Hello , i'm use nuxtjs and feathersjs

i have next problem

NuxtServerError
Invalid token: expired

node_modules/feathers-authentication-client/lib/passport.js

        return Promise.reject(new Error('Invalid token: expired'));

this message after 			return feathersClient.passport.verifyJWT(accessToken)

how refresh? or clear cookies with oldest token

**Comment by daffl** [comment]
You will have to clear the cookies yourself. There is no built-in support for refresh tokens so the user will have to log in again.
