### ISSUE TITLE
authentication - Method: remove

### ISSUE THREAD

**Issue by Terran47** [feathersjs/authentication#662]
### Steps to reproduce
Good afternoon, tell me how to make sure that the session is not interrupted? After 5 minutes of inactivity, authorization removed, and I can not make requests without errors

---------------------------
app.js
const path = require('path');
const favicon = require('serve-favicon');
const compress = require('compression');
const cors = require('cors');
const helmet = require('helmet');
const bodyParser = require('body-parser');

const feathers = require('feathers');
const configuration = require('feathers-configuration');
const hooks = require('feathers-hooks');
const rest = require('feathers-rest');
const socketio = require('feathers-socketio');

const handler = require('feathers-errors/handler');
const notFound = require('feathers-errors/not-found');

const middleware = require('./middleware');
const services = require('./services');
const appHooks = require('./app.hooks');

const sequelize = require('./sequelize');
const easyimg = require('easyimage');

const authentication = require('./authentication');

var fs = require('fs');
const app = feathers();

// Load app configuration
app.configure(configuration());
// Enable CORS, security, compression, favicon and body parsing
app.use(cors());
app.use(helmet());
app.use(compress());
app.use(bodyParser.json({
	limit: '50mb'
}));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(favicon(path.join(app.get('public'), 'favicon.ico')));
// Host the public folder
app.use('/', feathers.static(app.get('public')));

// Set up Plugins and providers
app.configure(hooks());
app.configure(sequelize);
app.configure(rest());
app.configure(socketio({
  pingInterval:1000000,
  pingTimeout:50000000
}));

// Configure other middleware (see `middleware/index.js`)
app.configure(middleware);
app.configure(authentication);
// Set up our services (see `services/index.js`)
app.configure(services);
// Configure a middleware for 404s and the error handler
app.use(notFound());
app.use(handler());

app.hooks(appHooks);

module.exports = app;

Android
**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System*Centos 6*:

**React Native Version*0.50*:

**Module Loader**:

**Comment by daffl** [comment]
Try forcing the `websocket` transport on the Socket.io client connection:

```js
const socket = io('http://api.my-feathers-server.com', {
  transports: ['websocket'],
  forceNew: true
});
```
