### ISSUE TITLE
Problems when integrating with strategy of 'passport-wechat'

### ISSUE THREAD

**Issue by flight9** [feathersjs/authentication#666]
Sorry, I have to open a new ticket, because the old one has been closed: https://github.com/feathersjs/authentication/issues/659

@daffl
> What's wrong with https://github.com/liangyali/passport-wechat?

## Promblem 1: 

I found a problem on configuation.
In https://github.com/liangyali/passport-wechat, it uses 'appID' and 'appSecret' as below:
```
passport.use(new WechatStrategy({
        appID: {APPID},
        name:{默认为wechat,可以设置组件的名字}
        appSecret: {APPSECRET},
        client:{wechat|web},
        callbackURL: {CALLBACKURL},
        scope: {snsapi_userinfo|snsapi_base},
        state:{STATE},
        getToken: {getToken},
        saveToken: {saveToken}
      },
      function(accessToken, refreshToken, profile,expires_in, done) {
        return done(err,profile);
      }
));
```
But in @feathersjs/authentication-oauth2, it uses 'clientID' and 'clientSecret':
```
app.configure(oauth2({
  name: 'facebook',
  Strategy: FacebookStrategy,
  clientID: '<your client id>',
  clientSecret: '<your client secret>',
  scope: ['public_profile', 'email']
}));
```
This difference of naming may cause an error when you try to use authentication-oauth2 to initialize wechat strategy.

**Comment by daffl** [comment]
You should be able to just pass the same options:

```js
app.configure(oauth2({
        name: 'wechat',
        Strategy: WechatStrategy,
        appID: {APPID},
        name:{默认为wechat,可以设置组件的名字}
        appSecret: {APPSECRET},
        client:{wechat|web},
        callbackURL: {CALLBACKURL},
        scope: {snsapi_userinfo|snsapi_base},
        state:{STATE},
        getToken: {getToken},
        saveToken: {saveToken}
}));
```

**Comment by flight9** [comment]
## Problem 2: 
In https://github.com/liangyali/passport-wechat/blob/48e3ea4706a9604fa13f91f0300767119080d32f/lib/strategy.js#L110
When it invoking 'verify' function, the 5th param is passed a time value, not a 'done' fuction.
But in @feathersjs/authentication-oauth2 the statement of 'verify' function is as this:
```
verify(req, accessToken, refreshToken, profile, done)
```
means the 5th param should be a 'done' function.
This difference of params defining may cause another running error: TypeError: done is not a function.

**Comment by daffl** [comment]
Can you try [customizing the verifier](https://docs.feathersjs.com/api/authentication/oauth2.html#verifier) and changing the signature accordingly?

```js
class WechatVerifier extends Verifier {
  // The verify function has the exact same inputs and 
  // return values as a vanilla passport strategy
  verify(req, accessToken, refreshToken, profile, expiresIn, done) {
    super.verify(req, accessToken, refreshToken, profile, done);
  }
}
```

**Comment by flight9** [comment]
@daffl 
> You should be able to just pass the same options:
```
app.configure(oauth2({
        name: 'wechat',
        Strategy: WechatStrategy,
        appID: {APPID},
        name:{默认为wechat,可以设置组件的名字}
        appSecret: {APPSECRET},
        client:{wechat|web},
        callbackURL: {CALLBACKURL},
        scope: {snsapi_userinfo|snsapi_base},
        state:{STATE},
        getToken: {getToken},
        saveToken: {saveToken}
}));
```
I tried, and got another err: 
```
Error: You must provide a 'clientID' in your authentication configuration or pass one explicitly
at Function.oauth2Auth (D:\VueWork\feathers-chat2\node_modules\@feathersjs\authentication-oauth2\lib\index.js:59:13)
```

**Comment by daffl** [comment]
Hm, looks like those are currently still required. Since they are not used, we can maybe just pass whatever:

```js
app.configure(oauth2({
        name: 'wechat',
        clientId: 'notused',
        clientSecret: 'notused',
        Strategy: WechatStrategy,
        appID: {APPID},
        name:{默认为wechat,可以设置组件的名字}
        appSecret: {APPSECRET},
        client:{wechat|web},
        callbackURL: {CALLBACKURL},
        scope: {snsapi_userinfo|snsapi_base},
        state:{STATE},
        getToken: {getToken},
        saveToken: {saveToken}
}));
```

Unfortunately I don't have a Wechat application set up I can try it out though 😞

**Comment by flight9** [comment]
## Problem3:
Inside default verify function logic, if we can't file user, it will call default _createEntity(data) to create a new user entry.
But at that time, we dont know username(email), userpassword, so not enough info to create a entry, or the user may already have an account inside our system, we just need to bind the existing account with the user's OAuth profile. 
Through createEntity(), how can I redirect current request to a signup/bind page and carrying the profile got from the provider to let current user to offer username/password then we can create a new account or bind an existing account with the profile?




editing...

**Comment by daffl** [comment]
So the signup itself is working now? You can redirect to the `signup`/`bind` page adding the oAuth access token to the query string (this will also allow you to get the profile again).

**Comment by flight9** [comment]
@daffl But how can I redirect inside verify() or _createEntity()? there is no Express 'res' I can use.

**Comment by flight9** [comment]
I'll provide my code later

**Comment by flight9** [comment]
I published the code I'm working on under https://github.com/flight9/feathers-chat2
(there is one config file of wechat appid/secret have been excluded, which I will send you via email later)

**Comment by flight9** [comment]
I was reminded of a question suddenly: it may be hard for you to run it, because of wechat's security policy.

The policy requires you to:
1. Map the server to a public domain(Can be accessed by the external network) first.
2. Set the domain in the security setting inside control panel of wechat account.
3. Visit the domain.com/auth/wechat only inside a wechat app client or a wechat [simulator](https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html).
Without above, you will recieve some prompt and fail.

The 3nd is easy to achieve, but for the first 2 steps, it may need you to [apply a new test account](https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login) of your own, and my appid/secret will become useless.

**Comment by flight9** [comment]
I think you may want to know the Wechat OAuth profile info, it's like this:
```
{    
"openid": "oW6aH0ditEHnptRI058xBw0pOBzg",
" nickname": "NICKNAME",
"sex":"1",
"province":"PROVINCE"
"city":"CITY",
"country":"COUNTRY",
"headimgurl":    "http://thirdwx.qlogo.cn/mmopen/g3MonUZtNHkdmzicIlibx6iaFqAc56vxLSUfpb6n5WKSYVY0ChQKkiaJSgQ1dZuTOgvLLrhJbERQQ4eMsv84eavHiaiceqxibJxCfHe/46",
"privilege":[ "PRIVILEGE1" "PRIVILEGE2"     ]
}
```

**Comment by daffl** [comment]
Feathers v4 authentication is now using [grant](https://github.com/simov/grant) instead of Passport for oAuth which has built-in Wechat support. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
