### ISSUE TITLE
config\default.json generated without callbackURL config needed to set redirect URL for Google Outh2

### ISSUE THREAD

**Issue by HarisHashim** [feathersjs/authentication#669]
### Steps to reproduce
Do  "feathers generate authentication" and choose Google oauth

config\default.json should have this for Google

``
"google": {
	"clientID": "xxxx",
	"clientSecret": "xxxx",
	"successRedirect": "/auth",
	"scope": [
		"profile openid email"
	]
}
``

- I need to change as bellow to change redirect URL. Otherwise I always get http://localhost:8080/auth/google/callback as redirect URL.

      "successRedirect": "http://aaa.bbb.cc/",
      to 
      "callbackURL": "http://aaa.bbb.cc/",

### Expected behavior
It looks like that successRedirect should be callbackURL. Something must have change!

**NodeJS version**: v6.11.2

**Operating System**: Ubuntu

**Browser Version**: Chrome Version 64.0.3282.140 (Official Build) (32-bit)

**Comment by daffl** [comment]
The idea is that you will be setting your `host` option properly in other environments (e.g. [NODE_ENV=production](https://github.com/feathersjs/feathers-chat/blob/master/config/production.json#L2)).
