### ISSUE TITLE
CLI command bug: 'Feathers generate authentication' produces bad working 'users' service

### ISSUE THREAD

**Issue by ganchikov** [feathersjs/authentication#670]
### Steps to reproduce
run cli command 'feathers generate authentication' with default service name for users ('users')
add hook for users create action (before hashPassword)

### Expected behavior
cli command should produce working users service

### Actual behavior
code of users service produced incorrectly  - when posting data (create), it is parsed incorrectly and results in an Object with the key equals to JSON data and value equals to '', e.g.:

Object {{"email" : "email@address.com", "password" : "12345"}: ""}

as a workaround i had to use Object.getOwnPropertyNames and use JSON.parse which produces correct object which is then asigned to context.data and retrieved by hook

### System configuration

**Module versions** (especially the part that's not working):
  "dependencies": {
    "@feathersjs/authentication": "^2.1.5",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.3",
    "@feathersjs/authentication-oauth2": "^1.0.3",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.1",
    "@feathersjs/feathers": "^3.1.4",
    "@feathersjs/socketio": "^3.2.1",
    "app-root-path": "^2.0.1",
    "compression": "^1.7.1",
    "cors": "^2.8.4",
    "feathers-mongoose": "^6.1.0",
    "helmet": "^3.12.0",
    "mongoose": "^5.0.14",
    "morgan": "^1.9.0",
    "passport-auth0": "^0.6.1",
    "serve-favicon": "^2.5.0",
    "winston": "^2.4.1"
  },
  "devDependencies": {
    "eslint": "^4.15.0",
    "feathers-memory": "^2.1.1",
    "mocha": "^5.0.5",
    "request": "^2.83.0",
    "request-promise": "^4.2.2",
    "shx": "^0.2.2"
  }

**NodeJS version**:
v 8.9.4

**Operating System**:
Win 7 x64

**Browser Version**:
n/a

**React Native Version**:
n/a

**Module Loader**:
npm 5.6.0

**Comment by daffl** [comment]
I'm not sure I am following the issue and wasn't able to reproduce something that breaks. Can you share a repository that demonstrates the problem?

**Comment by ganchikov** [comment]
here is git: https://github.com/ganchikov/feathers-bug
re-tested, it was an issue with specifying header:
this one is working:
curl http://localhost:3030/users/ -H **'Content-Type: application/json'** --data-binary '{"email":"sample@sample.com", "password":"12345"}'
this one is not (see extra space between Content-Type and ':' symbol):
curl http://localhost:3030/users/ -H **'Content-Type : application/json'** --data-binary '{"email":"sample@sample.com", "password":"12345"}'
it is likely not a bug but lack of my attention, so feel free to close it

**Comment by daffl** [comment]
That's how [HTTP headers are specified](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) so I don't think this is a Feathers specific issue (Node's internal HTTP header parser will probably never pick it up). Good to know though, I never noticed that behaviour!
