### ISSUE TITLE
Is there anyway to load a secret at runtime?

### ISSUE THREAD

**Issue by cdrandin** [feathersjs/authentication#671]
### Steps to reproduce

I have been trying to override `app.set('auth', authOptions);` and `app.set('authentication', authOptions);`. Which none have worked `authenticate('jwt')` already stores what authOptions it cares about already. I could pass in the `authenticate('jwt', OPTIONS_HERE)`, but would have to delay the whole process just to wait for the promise to return for the key.

Possibly I am going about this the wrong way.

This is how I am trying to get my key.

```Javascript
  const Datastore = require('@google-cloud/datastore');
  const datastore = new Datastore();
  datastore.runQuery(datastore.createQuery('Settings').select('MY_SECRET'))
  .then((res) => {
    console.log('Successfully loaded secret');
    const authOptions = app.get('authentication');

    // This doesn't using the proper secret when trying to verify JWT token
    authOptions.secret = res[0][0]['MY_SECRET'];
    app.set('auth', authOptions);
    app.set('authentication', authOptions);
    console.log('New secret:', app.get('authentication').secret);
  })
```

### Expected behavior
The new secret should be used to throughout feathers app.

### Actual behavior
The secret that was loaded in at runtime isn't being used since authenticate was called prior to loading the secret and didn't want to slow down the rest of the process.

System configs were omitted since this seems more like how do you really do it than a properly with feathers.

**Comment by daffl** [comment]
Have you tried setting the nested `secret` property? 

```js
app.get('authentication').secret = '12324';
```

**Comment by daffl** [comment]
Feathers v4 authentication supports dynamically setting options in a single place and at runtime.

Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
