### ISSUE TITLE
Authentication local strategy not working with a Custom User service

### ISSUE THREAD

**Issue by LetsDoIt-** [feathersjs/authentication#672]
I am using a custom service to manage users and when i try to authenticate using email password it gives an error : a record with email of 'sgd@sgd100.com' did not exist and Invalid login error 

But when i changed to in-memory user service it works like a charm. 

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): Feathers Auth 2.1.5

**NodeJS version**: 8.7.0

**Operating System**: Mac OS X

**Browser Version**: 

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Your custom service has to support

- And `id` property which contains the name of the id field
- Support a `find` method with `params.query = { email }` (`email` or `usernameField `)
