### ISSUE TITLE
Is there a way to get req.user without using the authentication middleware?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [feathersjs/authentication#675]
WouldJjust grab the JWT from the cookie, and verify that? How would I do that from the server? (The Feathers's express server, which is where I'm hosting both the front-end and back end)

**Comment by daffl** [comment]
The `authenticate` Express middleware does all of that for you, why wouldn't you use it?

**Comment by daffl** [comment]
Ah, I see. You could copy the code (https://github.com/feathersjs/authentication/blob/master/lib/express/authenticate.js) and modify it to what you need then.

**Comment by bertho-zero** [comment]
Would an `ignoreFails` option not be enough? I have already had the case several times and it is true that creating this piece of code is not complicated but a little tedious.

**Comment by ThatNerdyPikachu** [comment]
If the authenticate middleware is used, then that route sends a 401, no?

**Comment by ThatNerdyPikachu** [comment]
@daffl

**Comment by daffl** [comment]
If you don't want to/can't use the middleware at the moment copying the code and modifying it to what you need is the way to go. I'll include an option to not error in the next version.

**Comment by ThatNerdyPikachu** [comment]
Alright, thanks!
Mind posting something here when that's done?

**Comment by qazs** [comment]
Hi @daffl, I would also like to have mixed mode authentication, meaning unauthenticated user is still able to access the data. Any update on this?
