### ISSUE TITLE
hook.params.user is null using REST

### ISSUE THREAD

**Issue by hauckwill** [feathersjs/authentication#678]
Using the socketio transport, hook.params.user is populated and can be used in hooks. Using REST, however, I am able to authenticate but I see no user.

Here is what I get in the before hook:
```
debug: Hook Context {
  "type": "before",
  "method": "find",
  "path": "tags",
  "params": {
    "query": {},
    "route": {},
    "provider": "rest",
    "headers": {
      "content-type": "application/json",
      "authorization": "{TOKEN}",
      "cache-control": "no-cache",
      "postman-token": "7aae0712-7d16-4d67-9290-8935e5c3a698",
      "user-agent": "PostmanRuntime/7.1.1",
      "accept": "*/*",
      "host": "localhost:3030",
      "accept-encoding": "gzip, deflate",
      "connection": "keep-alive"
    }
  }
}
```

In my before all hooks I have authenticate('jwt').

Why is there a user param when using websockets? How do I enable this using REST?

**Comment by daffl** [comment]
Try setting the `Authorization` header to using the bearer scheme `"authorization": "Bearer {TOKEN}"`

**Comment by hauckwill** [comment]
Unfortunately not helping. Same problem.

I know authentication is happening because if I change a character of the JWT I get:
```
{
    "name": "NotAuthenticated",
    "message": "invalid algorithm",
    "code": 401,
    "className": "not-authenticated",
    "data": {
        "name": "JsonWebTokenError",
        "message": "invalid algorithm"
    },
    "errors": {}
}
```
...and none of my other hooks run. Using the correct JWT, my hooks after authenticate('jwt') _do_ run but without the params.user object.

**Comment by daffl** [comment]
How does the [decoded token look](https://jwt.io/) then? Does it have `userId`? Can you share a repository to reproduce the issue?

**Comment by hauckwill** [comment]
Here's the decoded token:
```
{
  "userId": 1,
  "iat": 1528215672,
  "exp": 1528302072,
  "aud": "https://yourdomain.com",
  "iss": "feathers",
  "sub": "anonymous",
  "jti": "0c83ca60-ffe5-4c63-87b5-2a9ff3bc7b2b"
}
```

Also, calling /authentication with my username and password does return the user object in the result, but it's not there on subsequent calls.

Unfortunately I'm unable to share the code at the moment (not mine to share).

**Comment by hauckwill** [comment]
Also, hook.params.user is present in the hooks in the /authentication service.

**Comment by hauckwill** [comment]
Figured it out.

Didn't realize socketio wasn't calling the /users service on every call to pull user data like REST was. One of my hooks was preventing REST from getting a user.

Is socketio not getting a user on each call normal behavior?

**Comment by daffl** [comment]
Trying to create a reproducible issue can help you to figure out the problem as well. I'm not able to reproduce it for example in the [feathers-chat](https://github.com/feathersjs/feathers-chat).

**Comment by daffl** [comment]
Currently yes but that will change in the next version (see https://github.com/feathersjs/authentication/issues/517)

**Comment by hauckwill** [comment]
Appreciate the help!

**Comment by abalad** [comment]
I'm having the same problem when making calls using the Rest Provider.
Some HOOks that I need to deal with the user do not get this value.
