### ISSUE TITLE
Customize response of authentication service

### ISSUE THREAD

**Issue by gavin771** [feathersjs/authentication#679]
### Steps to reproduce
Try to GET the /authentication route

### Expected behavior
I expect that if I add an error section to the hooks of authentication I will be able to catch and customize the response sent to the user, specifically in a json format

### Actual behavior
I get an html response of MethodNotAllowed

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
 "@feathersjs/authentication": "^2.1.5",
 "@feathersjs/errors": "^3.3.0",

**NodeJS version**:
v9.11.1

**Comment by daffl** [comment]
The HTML response is returned by the [errorHandler](https://docs.feathersjs.com/api/express.html#expresserrorhandler). You will always get JSON error if you set the `Accept` header to `application/json` or `html: false` in the error handler configuration.

**Comment by gavin771** [comment]
ok thanks
