### ISSUE TITLE
authentication-local with Sequelize doesn't protect password on Sequelize error 

### ISSUE THREAD

**Issue by tdolphin** [feathersjs/authentication#691]
### Steps to reproduce

1. feathers generate authentication
2. use Sequelize (postgres)
3. users.model.js has email field as unique
4. create another user with same email
5. Sequelize error sent in BadRequest 400 contains password.
6. Add hook to error in users.hooks.js has no effect.
` error: {
    all: [protect('errors')],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }`
Tried variation:
`protect('errors[0].instance.password')`
Tried using omit directly with no effect.

### Expected behavior
protect/omit in error hooks should have effect

### Actual behavior
protect/omit in error hooks not called.
`throw feathersError;` feathers-sequelize/lib/utils

### System configuration

**Module versions** (especially the part that's not working): 
authentication-local 1.2.1
feathers-sequelize 3.1.2

**NodeJS version**: 10.7

**Operating System**: windows 10

**Browser Version**: postman
![sequelize_protecterror](https://user-images.githubusercontent.com/7492772/43547401-297f2ab8-95a9-11e8-82a6-089ce7f76a33.png)

**Module Loader**: npm

**Comment by daffl** [comment]
Similar to https://github.com/feathersjs/errors/issues/115 - basically [feathers-sequelzize](https://github.com/feathersjs-ecosystem/feathers-sequelize) should not really pass through - or clean up - any of those errors.

Additionally, it is true, the `protect` hook in https://github.com/feathersjs/authentication-local/blob/master/lib/hooks/protect.js should also do this for `context.error`

**Comment by daffl** [comment]
This has been done in the latest `feathers-sequelize`.
