### ISSUE TITLE
Accessing client SSL certificate from authenticate hook

### ISSUE THREAD

**Issue by cjbland** [feathersjs/authentication#693]
### Steps to reproduce

1. Create a new project with authentication
2. Add `passport-client-cert` to `package.json`
3. Include `passport-client-cert` as one of the available authentication strategies
4. Send a `POST` to the `/authentication` endpoint with a valid client SSL certificate
5. The system generates an error that it cannot read property 'authorized' of undefined - [see here](https://github.com/ripjar/passport-client-cert/blob/90e185cafcbe0f88c8ebedf52274a4fff94265fd/src/index.js#L27)

- [x] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

I'm trying to use [passport-client-cert](https://github.com/ripjar/passport-client-cert) as one of the authentication strategies for our internal project. All of our users have PKI certificates assigned to them and we are trying to validate the cert when they access the API. The problem we are running into is `req.socket` is coming back as undefined from within the `authenticate` function.

I've gone through the Feathers code and documentation and it appears that `req` is the contents of the `hook` [as seen here](https://github.com/feathersjs/authentication/blob/10bfcd6dc7b17619606d0dd571a99b04d1ab0959/lib/hooks/authenticate.js#L46). Hooks do not have the TLS socket associated with it like the normal request does. Is there an easy way to get the user's certificate in a middleware and make it available to the `authenticate` function? Is there a better way to accomplish this? Thanks for any help.

### Expected behavior
It would be nice if the req/hook had the client's certificate (from the `req.socket.getPeerCertificate()` function).

### Actual behavior
The `req` has the hook contents which does not include any client certificate information.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/feathers v3.1.7
@feathersjs/authentication v2.1.7
passport v0.4.0
passport-client-cert v2.1.0

**NodeJS version**:
8.9.4

**Operating System**:
CentOS 7.5

**Browser Version**:
curl v7.29.0
Firefox v52.7.2

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
`req` is not the content of the hook but [this FAQ](https://docs.feathersjs.com/faq/readme.html#how-do-i-access-the-request-object-in-hooks-or-services) should answer your question.

**Comment by cjbland** [comment]
Thanks for the reply, this helped and worked. I'm able to grab the client's certificate in the middleware and then have it passed to the hook's params. From there I can get it in the Passport strategy. Thanks again.
