### ISSUE TITLE
using {allowUnauthenticated: true} but still receive 401 in client

### ISSUE THREAD

**Issue by musicformellons** [feathersjs/authentication#695]
I tried using the option 'allowUnauthenticated' by changing all `authenticate('jwt')` (or similar) into `authenticate('jwt', {allowUnauthenticated: true})` on my serverside. I would expect to not receive a 401 in case of non-authentication on my client, but I still do receive in my browser console:
`NotAuthenticated {type: "FeathersError", name: "NotAuthenticated", message: "Could not find stored JWT and no authentication strategy was given", code: 401, className: "not-authenticated", …}`

**Comment by daffl** [comment]
This is a client side error from [app.authenticate()](https://docs.feathersjs.com/api/authentication/client.html#appauthenticate). In that case your app can just proceed making unauthenticated requests.

**Comment by daffl** [comment]
It does but the client does not know that you set `allowUnauthenticated` on the server. Where the error is coming from shows in the stack trace.

If you want to make unauthenticated requests either first check if a `feathers-jwt` is in `localStorage` or ignore the error.

**Comment by musicformellons** [comment]
Ok, thanks!
