### ISSUE TITLE
How can I verify a user by local strategy on client without real authentication?

### ISSUE THREAD

**Issue by flight9** [feathersjs/authentication#704]
How can I verify a user by username/password(like local strategy) on client without call authenticate() to really login?

**Comment by flight9** [comment]
@daffl I'm using vuex on client and I can't get `service('authentication')` directly, I tried this:
```
...mapActions('authentication', {  createAuthentication: 'create'}),
```
but failed with error: `[vuex] module namespace not found in mapActions(): authentication/`

**Comment by flight9** [comment]
I found in feathers-vuex a class which can help me get service:
```
import feathersClient from '@/api/feathers-client'

const authService = feathersClient.service('/authentication')
  let res = await authService.create({
    strategy: 'local',
    email,
    password
  })
```

@daffl But then another question is even if I pass in a wrong email or password, the create() will always return an accessToken, that can't help me verify an invalid user.

**Comment by flight9** [comment]
I have to logout first, then use authentication.create() or auth/authenticate() to verify a user

**Comment by daffl** [comment]
Yes. This is a known issue and tracked in https://github.com/feathersjs/feathers/issues/1017. Closing this one since this repository will be moved.
